- source/documentation/index.md
Intended to give a very brief but useful overview of what Kubernetes is, how it works, what the major resource types are, what extra resource types and services we've added, and some links to resources elsewhere - any additions to the _Further Kubernetes Information_ section gratefully received.
> Add Kubernetes overview to docs

- source/documentation/index.md
This adds minimal docs for accessing ArgoCD.
> Add ArgoCD docs

- source/documentation/index.md
Add access instructions to the cluster
> Add access instructions to the cluster

- README.md
Nothing fancy, just adding a link to make it easier to find.
> Add: link to live documentation site

- source/documentation/index.md
Tested: copy-pasted the commands to check that they work as intended. Checked links.
[Trello](https://trello.com/c/1k2eVCZS/670)
> Add some basic examples of how to access app logs.

- source/documentation/index.md
This doc is a how to guide for installing current tool set used for interacting with GOV.UK Kubernetes Cluster.
https://trello.com/c/1k2eVCZS/670-good-enough-user-docs
> Tools setup user doc.

- source/documentation/index.md
https://trello.com/c/1k2eVCZS/670-good-enough-user-docs
> Github Actions user doc.

- source/documentation/index.md
[Trello](https://trello.com/c/1k2eVCZS/670)
> Use subheadings in the logs section.

- source/documentation/index.md
[Trello](https://trello.com/c/1k2eVCZS/670)
> Fix typos.

- source/documentation/index.md
This lists the cluster-level integrations with AWS services we have installed.
https://trello.com/c/1k2eVCZS/670-good-enough-user-docs
> Add AWS Integrations section

- source/get-started/set-up-tools/index.html.md.erb
Document how to set up the kubectl, helm, gds-cli and aws-vault tools. Part of the "Get started" section.
https://trello.com/c/wvQhoyOd/799-document-how-to-set-up-the-tools-needed-to-use-the-platform
> Document how to set up tools to use the platform

- source/get-started/access-eks-cluster/index.html.md.erb
Documents how to access the EKS cluster, including:
- defining the roles
- how to select a role and environment
- how to test your access
> Access EKS cluster

- source/manage-app/release-new-version/index.html.md.erb
Documents how a new version of an app is released automatically.
https://trello.com/c/jp9nlQ0C/909-document-how-to-release-a-new-version-of-your-app
> Document how a new version of an app is released automatically

- source/manage-app/create-new-env/index.html.md.erb
Document how to create a new environment. The process is as follows:
- complete the prerequisites
- create secrets for the new environment
- create a new environment
- deploy the Terraform modules and delete the configmap
- create the Signon API token
- check the environment is working
> Document how to create a new environment

- source/manage-app/manage-state/index.html.md.erb
Minor changes to bring new argo app sync content into gov.uk style
> Minor style changes to new argo app sync content 

- source/manage-app/scale-app/index.html.md.erb
Document how to scale an app by scaling replicas and resources.
> Document how to scale an app

- source/manage-incident/debug-app/index.html.md.erb
Add documentation on debugging your app, covering what to do if:
- the app's functional configuration is wrong
- not enough resources are allocated to the app
- the app does not have access to required AWS services
- the GOV.UK Kubernetes platform is malfunctioning
This content also has some general debugging advice.
> Document how to debug your app

- source/manage-app/manage-secrets/index.html.md.erb
Document how to add secrets to your app on the Kubernetes platform.
> Document how to add secrets

- source/manage-app/access-ci-cd/index.html.md.erb
See alphagov/govuk-helm-charts#615.
> Rename govuk-rails-app to generic-govuk-app.

- source/get-started/tutorials/app-config-deploy-helm-chart/index.html.md.erb
- source/get-started/tutorials/app-update-deploy-monitor-logs/index.html.md.erb
- source/get-started/tutorials/index.html.md.erb
Add tutorials to help developers familiarise themselves with developing on the kubernetes cluster.
https://trello.com/c/X357aij8/988-write-up-codelab-sessions
> Add tutorials

- Dockerfile
The current version isn't supported anymore.
https://trello.com/c/PMsAXSoT/3029-review-govuks-usage-of-node-2
> Use Node.js 16

- source/get-started/index.html.md.erb
- source/get-started/tutorials/app-update-deploy-monitor-logs/index.html.md.erb
Update the tutorials so that we can capture some feedback to help improve them. 
Also added a note to let devs know that no set up is needed to run the tutorials.
https://trello.com/c/b9dWacXz/1056-run-tutorials-mob-session-and-gather-feedback
> Add feedback link tutorial

- source/get-started/tutorials/app-config-deploy-helm-chart/index.html.md
- source/get-started/tutorials/app-update-deploy-monitor-logs/index.html.md
Update the docs to clarify that the govuk-helm-charts repo has symlinked value files, show the version release in the test app response and update the duration for the app deployment which can be around 10 minutes.
https://trello.com/c/ybrBghB7/1113-review-feedback-and-make-any-relevant-changes-to-tutorials
> Update replatform tutorials

- source/manage-app/get-app-info/index.html.md
This tripped me up as it wasn't clear (as an outsider) what the possible namespaces are, nor that the main namespace we'll end up using is `apps`.
> Document how to see available namespaces and set a default

- README.md
- config/tech-docs.yml
- source/fix-app/index.html.md
- source/manage-app/scale-app/index.html.md
> Fix link in README and use relative links in docs.

- source/manage-app/scale-app/index.html.md
Updating following the 2nd line drill - https://trello.com/c/fPEXeNU4/2019-2nd-line-drill-scaling-up-an-application
> Update scale-app documentation
